name: "Workspace-secret-id-update"
on:
  schedule:
    - cron:  '*/15 * * * *'    # At every 15th minute

jobs:
  vault-action:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.3.1
        with:
          url: https://vault-cluster.vault.2ee13667-f51e-4b79-993d-7cb501bf0c9f.aws.hashicorp.cloud:8200
          method: approle
          roleId: cf003c80-c0e6-1e01-7716-a23204e1c616
          secretId: fe3c94e7-d632-ebd0-9c56-fd28ee711d31
          