name: "Workspace-secret-id-update"
on:
  schedule:
    - cron:  '*/15 * * * *'    # At every 15th minute

jobs:
  vault-action:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.3.1
        with:
          url: https://vault.mycompany.com:8200
          method: approle
          roleId: ${{ secrets.roleId }}
          secretId: ${{ secrets.secretId }}
          caCertificate: ${{ secrets.VAULTCA }}