name: "Workspace-secret-id-update"
on:
  schedule:
    - cron:  '*/1 * * * *'    # At every 15th minute

jobs:
  vault-action:
    runs-on: ubuntu-latest
    steps:
      - name: Get Vault token
        run: |
          cd /tmp
          echo 1. Install Vault
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install vault
          echo 2. Set Vault addr & create Vault token
          export VAULT_ADDR=${{ secrets.VAULT_ADDR }}
          export VAULT_NAMESPACE=${{ secrets.VAULT_NAMESPACE }}
          export VAULT_TOKEN=$(vault token create -policy=approle-A -format json | jq -r ".auth.client_token")
          echo 3. TFE api to create namespace
          vi /tmp/payload.json -<<EOF
          {
            "data": {
              "id":"${{ WORK_VARS }}",
              "attributes": {
                "key":"test_key_name",
                "value":"${{ VAULT_TOKEN }}",
                "description":"some description",
                "category":"terraform",
                "hcl": false,
                "sensitive": false
              },
              "type":"vars"
            }
          }

          cat payload.json

          