name: "Workspace-secret-id-update"
on:
  schedule:
    - cron:  '*/1 * * * *'    # At every 15th minute
  workflow_dispatch:

jobs:
  vault-action:
    runs-on: ubuntu-latest
    steps:
      - name: Get Vault token
        run: |
          cd /tmp
          echo 1. Install Vault
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install vault
          echo 2. Set Vault addr & create Vault token
          export VAULT_ADDR=${{ secrets.VAULT_ADDR }}
          export VAULT_NAMESPACE=${{ secrets.VAULT_NAMESPACE }}
          export VAULT_TOKEN=$(vault write auth/approle/login role_id=${{ secrets.VAULT_ROLE_ID }} secret_id=${{ secrets.VAULT_SECRET_ID }}|grep -w "token"| awk '{ print $NF }')
          echo 3. TFE api to create namespace
          echo "{
            "data": {
              "id":"${{ secrets.WORK_VARS }}",
              "attributes": {
                "key":"test_key_name",
                "value":"$VAULT_TOKEN",
                "description":"Initial vault token",
                "category":"terraform",
                "hcl": false,
                "sensitive": false
              },
              "type":"vars"
            }
          }" > payload.json | cat payload.json
          
          cat payload.json
          curl \
            --header "Authorization: Bearer ${{ secrets.TFE_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --request PATCH \
            --data @payload.json \
            https://app.terraform.io/api/v2/workspaces/${{ secrets.WORKSPACE_ID }}/vars/${{ secrets.WORK_VARS }}
          